### ISSUE TITLE
<template functional> is no longer supported in Vue 3

### ISSUE THREAD

**Issue by KnowsCount** [dewfall123/vitepress-for-component#27]
**Describe the bug**
I ran `yarn create vlib` and then completed all the choices, under vue-multiple-components mode, whereafter I ran `npm install`, showing logs provided below

```
➜  fuckup npm install 
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated rollup-plugin-alias@2.2.0: This module has moved and is now available at @rollup/plugin-alias. Please update your dependencies. This version is no longer maintained.
npm WARN deprecated rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.

added 1527 packages, and audited 1528 packages in 7m

110 packages are looking for funding
  run `npm fund` for details

7 vulnerabilities (3 moderate, 4 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

I, then, ran `npm run dev`, having this as the output:

```
➜  fuckup npm run dev

> fuckup@0.0.1 dev
> vitepress-fc dev --root=docs

vitepress v0.14.0
vite v2.0.5
root = docs/.temp
copy to .temp success.
Pre-bundling dependencies:
  vue
(this will be run only when your dependencies or config have changed)

  vite v2.0.5 dev server running at:

  > Local:    http://localhost:3000/
  > Network:  http://192.168.0.100:3000/
[@vue/compiler-sfc] <script setup> is still an experimental proposal.
Follow its status at https://github.com/vuejs/rfcs/pull/227.

[@vue/compiler-sfc] When using experimental features,
it is recommended to pin your vue dependencies to exact versions to avoid breakage.

[@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.

[@vue/compiler-sfc] `defineEmit` is a compiler macro and no longer needs to be imported.

12:53:08 [vite] Internal server error: <template functional> is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal <template> instead.
  Plugin: vite:vue
  File: /Users/admin/projects/vue/fuckup/node_modules/vitepress-for-component/dist/client/theme-default/components/icons/ArrowLeft.vue
      at /Users/admin/projects/vue/fuckup/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:196:37
      at Array.forEach (<anonymous>)
      at Object.parse (/Users/admin/projects/vue/fuckup/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:182:18)
      at createDescriptor (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4392:52)
      at transformMain (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4694:32)
      at TransformContext.transform (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:5016:16)
      at Object.transform (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:46027:53)
      at async transformRequest (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61631:29)
      at async /Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61739:32
12:53:09 [vite] Internal server error: <template functional> is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal <template> instead.
  Plugin: vite:vue
  File: /Users/admin/projects/vue/fuckup/node_modules/vitepress-for-component/dist/client/theme-default/components/icons/ArrowRight.vue
      at /Users/admin/projects/vue/fuckup/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:196:37
      at Array.forEach (<anonymous>)
      at Object.parse (/Users/admin/projects/vue/fuckup/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:182:18)
      at createDescriptor (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4392:52)
      at transformMain (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4694:32)
      at TransformContext.transform (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:5016:16)
      at Object.transform (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:46027:53)
      at async transformRequest (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61631:29)
      at async /Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61739:32
12:53:09 [vite] Internal server error: <template functional> is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal <template> instead.
  Plugin: vite:vue
  File: /Users/admin/projects/vue/fuckup/node_modules/vitepress-for-component/dist/client/theme-default/components/icons/OutboundLink.vue
      at /Users/admin/projects/vue/fuckup/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:196:37
      at Array.forEach (<anonymous>)
      at Object.parse (/Users/admin/projects/vue/fuckup/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:182:18)
      at createDescriptor (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4392:52)
      at transformMain (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4694:32)
      at TransformContext.transform (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:5016:16)
      at Object.transform (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:46027:53)
      at async transformRequest (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61631:29)
      at async /Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61739:32
12:53:30 [vite] Internal server error: /Users/admin/projects/vue/polyeth-docs/node_modules/vitepress/dist/client/theme-default/components/icons/OutboundLink.vue has no corresponding SFC entry in the cache. This is a @vitejs/plugin-vue internal error, please open an issue.
      at getDescriptor (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4412:11)
      at Context.load (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4991:28)
      at Object.load (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:46008:50)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async transformRequest (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61574:24)
      at async /Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61739:32
12:53:30 [vite] Internal server error: /Users/admin/projects/vue/polyeth-docs/node_modules/vitepress/dist/client/theme-default/components/NavDropdownLinkItem.vue has no corresponding SFC entry in the cache. This is a @vitejs/plugin-vue internal error, please open an issue.
      at getDescriptor (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4412:11)
      at Context.load (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4991:28)
      at Object.load (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:46008:50)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async transformRequest (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61574:24)
      at async /Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61739:32
12:53:31 [vite] Internal server error: <template functional> is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal <template> instead.
  Plugin: vite:vue
  File: /Users/admin/projects/vue/fuckup/node_modules/vitepress-for-component/dist/client/theme-default/components/icons/ArrowRight.vue
      at /Users/admin/projects/vue/fuckup/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:196:37
      at Array.forEach (<anonymous>)
      at Object.parse (/Users/admin/projects/vue/fuckup/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:182:18)
      at createDescriptor (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4392:52)
      at transformMain (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4694:32)
      at TransformContext.transform (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:5016:16)
      at Object.transform (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:46027:53)
      at async transformRequest (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61631:29)
      at async /Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61739:32
12:53:31 [vite] Internal server error: <template functional> is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal <template> instead.
  Plugin: vite:vue
  File: /Users/admin/projects/vue/fuckup/node_modules/vitepress-for-component/dist/client/theme-default/components/icons/ArrowLeft.vue
      at /Users/admin/projects/vue/fuckup/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:196:37
      at Array.forEach (<anonymous>)
      at Object.parse (/Users/admin/projects/vue/fuckup/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:182:18)
      at createDescriptor (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4392:52)
      at transformMain (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4694:32)
      at TransformContext.transform (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:5016:16)
      at Object.transform (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:46027:53)
      at async transformRequest (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61631:29)
      at async /Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61739:32
12:53:31 [vite] Internal server error: <template functional> is no longer supported in Vue 3, since functional components no longer have significant performance difference from stateful ones. Just use a normal <template> instead.
  Plugin: vite:vue
  File: /Users/admin/projects/vue/fuckup/node_modules/vitepress-for-component/dist/client/theme-default/components/icons/OutboundLink.vue
      at /Users/admin/projects/vue/fuckup/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:196:37
      at Array.forEach (<anonymous>)
      at Object.parse (/Users/admin/projects/vue/fuckup/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:182:18)
      at createDescriptor (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4392:52)
      at transformMain (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:4694:32)
      at TransformContext.transform (/Users/admin/projects/vue/fuckup/node_modules/@vitejs/plugin-vue/dist/index.js:5016:16)
      at Object.transform (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:46027:53)
      at async transformRequest (/Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61631:29)
      at async /Users/admin/projects/vue/fuckup/node_modules/vite/dist/node/chunks/dep-e0f09032.js:61739:32
```

**To Reproduce**
see **Describe the bug**

**Expected behavior**
to, not to put too fine a point on it, work.

**System Info**
- vitepress version: ?
- vite version: ^2.0.1
- Node version: v14.15.4
- OS version: macOS 10.14.6

**Additional context**
nothing more.

**Comment by dewfall123** [comment]
Try `yarn update vitepress-for-component` or run `yarn create vlib` again(The template has been updated).  It should be a problem with  vitepress-for-component's version.

**Comment by KnowsCount** [comment]
closed as solved. thanks!
