### ISSUE TITLE
升级之后

### ISSUE THREAD

**Issue by DengRiGuang** [dewfall123/vitepress-for-component#28]
copy to .temp success.
failed to start server. error:
 Error: Cannot find module '/Users/a123/Documents/My/libs/docs/.temp/.vitepress/config.js'
Require stack:
- /Users/a123/Documents/My/libs/node_modules/vitepress-for-component/dist/node/config.js
- /Users/a123/Documents/My/libs/node_modules/vitepress-for-component/dist/node/server.js
- /Users/a123/Documents/My/libs/node_modules/vitepress-for-component/dist/node/index.js
- /Users/a123/Documents/My/libs/node_modules/vitepress-for-component/dist/node/cli.js
- /Users/a123/Documents/My/libs/node_modules/vitepress-for-component/bin/vitepress-fc.js

**Comment by dewfall123** [comment]
提供下可复现仓库？ 我试了下这个仓库 （https://github.com/DengRiGuang/libs.git） 没能复现问题

**Comment by DengRiGuang** [comment]
> 提供下可复现仓库？ 我试了下这个仓库 （[https://github.com/DengRiGuang/libs.git）](https://github.com/DengRiGuang/libs.git%EF%BC%89) 没能复现问题

感觉是配置拷贝的问题，这个仓库可以复现，第一次, npm run dev后，停掉，在npm run dev，就会出现

**Comment by dewfall123** [comment]
还是复现不了哦 
 “copy to .temp success.“ 这个日志正常来说意味着root目录下所有文件复制到了temp临时目录，但是又找不到“.temp/.vitepress/config.js”文件，线索有点不够。

> 感觉是配置拷贝的问题，这个仓库可以复现，第一次, npm run dev后，停掉，在npm run dev，就会出现

**Comment by DengRiGuang** [comment]
> 还是复现不了哦
> “copy to .temp success.“ 这个日志正常来说意味着root目录下所有文件复制到了temp临时目录，但是又找不到“.temp/.vitepress/config.js”文件，线索有点不够。
> 
> > 感觉是配置拷贝的问题，这个仓库可以复现，第一次, npm run dev后，停掉，在npm run dev，就会出现

完整的日志，信息就这个
copy to .temp success.
failed to start server. error:
 Error: ENOENT: no such file or directory, lstat '/Users/a123/Desktop/libs/docs/.temp/.vitepress/config.js'
    at Object.realpathSync (fs.js:1728:7)
    at toRealPath (internal/modules/cjs/loader.js:344:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:487:24)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at resolveUserConfig (/Users/a123/Desktop/libs/node_modules/vitepress-for-component/dist/node/config.js:51:40)
    at async resolveSiteData (/Users/a123/Desktop/libs/node_modules/vitepress-for-component/dist/node/config.js:62:24)
    at async Object.resolveConfig (/Users/a123/Desktop/libs/node_modules/vitepress-for-component/dist/node/config.js:18:18) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/Users/a123/Desktop/libs/docs/.temp/.vitepress/config.js'

然后，我自己克隆下来，第二次重跑就报这个，你那不会，那就奇怪了
